### ISSUE TITLE
New actor for armour on ground

### ISSUE THREAD

**Issue by LenaTheWolfess** [SlavomirSlovenkai/MMO#10]

**Comment by mithray** [comment]
I made armor stands for all the helmets and the armor. I think this will look a lot better, but I haven't tested it as your last few commits seem to have broken the game :-). Let me know what you think of it. I think it's better this way because everything can be seen a bit more clearly. But the swords and bow are probably more difficult to see, and they haven't been modified.

No problem if you don't want to accept this or any of my other commits. Just doing what I can.

**Comment by LenaTheWolfess** [comment]
could be used in some cases, but would not work well when droping equipment from inventory, sudenly there would be that wood cross
